#!/usr/bin/env bash
# Auto-generated by epic plugin — runs on SessionStart.
# Installs the epic-harness binary if missing (Node.js fallbacks still work without it).

set -euo pipefail

PLUGIN_BIN="${CLAUDE_PLUGIN_ROOT:-}/hooks/bin/epic-harness"

# Already available — nothing to do
if test -x "$PLUGIN_BIN" || command -v epic-harness >/dev/null 2>&1; then
  exit 0
fi

echo "[epic plugin] epic-harness binary not found — installing..."

if command -v cargo-binstall >/dev/null 2>&1; then
  cargo binstall -y --no-confirm epic-harness
elif command -v cargo >/dev/null 2>&1; then
  cargo install epic-harness
else
  echo "[epic plugin] cargo not found. Install Rust from https://rustup.rs then restart Claude Code." >&2
fi

exit 0
